language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
  - master
  - develop
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless
before_deploy:
  script: ng build --prod --base-href https://dung1764.github.io/git-traning/
  on:
    branch: master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/git-tranning
  on:
    branch: master
